### ISSUE TITLE
BibleThump

### ISSUE THREAD

**Issue by Ravendwyr** [TwitchPlaysPokemon/pbr-movesets#120]
Sudden thought; should we rename BibleThump the Cubone to BigSad or nah?

**Comment by m4-used-rollout** [comment]
This Cubone https://github.com/TwitchPlaysPokemon/pbr-movesets/blob/master/pokesets/1%20HW_Standard/HW_Cubone.yaml#L26

**Comment by m4-used-rollout** [comment]
Polled the community and they said keep the name
