### ISSUE TITLE
Gauntlet runmons

### ISSUE THREAD

**Issue by mathfreak231** [TwitchPlaysPokemon/pbr-movesets#17]
hhhhhhh

**Comment by mathfreak231** [comment]
Done thru Blaze Black 2, all that's left is X. Most importantly Moth, but also a Hippopotas and Luvdisc that may or may not be notable.

**Comment by FrostedGeulleisia** [comment]
For further reference, I have the original Moth .pk6.
I'm missing the Hippopotas and Luvdisc though, I know Luvdisc was traded to someone in the community (in case I can't get M4 to give me the saves), but both might be obtainable from digging through [Reddo's API snapshots](https://red031000.com/snapshots/GauntletX/)
