### ISSUE TITLE
Reconsider nerf items on old Runmons

### ISSUE THREAD

**Issue by MathyFurret** [TwitchPlaysPokemon/pbr-movesets#23]
Like Speed Boost Rayquaza with Full Incense. As the meta is power creeping and focus is shifting from balance towards sets being authentic to the runs, older runmons can probably lose their nerfs.

**Comment by chaos-lord** [comment]
Agreed, we should move towards undoing the nerfs when possible.

**Comment by Torq-A** [comment]
Given that Runmons Reckoning was merged in, which should cover everything mentioned here, does that mean this particular issue is closed?
