### ISSUE TITLE
Prune dead branches

### ISSUE THREAD

**Issue by m4-used-rollout** [TwitchPlaysPokemon/pbr-movesets#65]
Please check the stale and holiday branches and ensure that any new changes they have that should be merged into master get applied to master. Many of them are too old to merge cleanly. After doing this, either delete the branch if you have the ability, or add a comment to this issue saying the branch can be deleted.

**Comment by Torq-A** [comment]
Looked over the [Christmas](https://github.com/TwitchPlaysPokemon/pbr-movesets/tree/christmas) branch - most of the moveset changes there were minor and were most likely done for balancing, but there were a few Xmas sets that weren't folded into the main version. You want me to add those into the existing pull I have set up?

**Comment by Torq-A** [comment]
[Let me know how this works for you.](https://github.com/TwitchPlaysPokemon/pbr-movesets/pull/71)

**Comment by m4-used-rollout** [comment]
Ok, I merged and deleted the other branches.
